### ISSUE TITLE
Problemas al intentar jugar una mano

### ISSUE THREAD

**Issue by leandromartin114** [francomamani00/desafio-modulo-6-ppt-online#2]
Hola Franco, estuve probando la web y va bien hasta que ingresas a la sala e intentas jugar. Me dejó crear la sala y también ingresar a la misma con ambos players sin inconvenientes. También me avisa ok si hay que esperar al otro jugador, pero una vez que elegís la mano ahí parece que no está tomando bien la jugada y se rompe. Me generó una situación como la de esta imagen en donde después de jugar con ambos players, me ruteo a la misma pantalla de espera. Te diría que en esa parte de tu app revises que el state esté trayendo en forma correcta la info que te pasa el back desde la room. Si la comunicación back/state esta todo ok, podés pasar a revisar el código de la page. Metele que ya casi está! Saludos.
![image](https://user-images.githubusercontent.com/84253648/183741070-d88f7c5b-0d1f-4b29-af6a-6d0753212741.png)

**Comment by francomamani00** [comment]
Hola buenas tardes! Gracias por responder! Intente varias veces y de diferentes formas pero no pude encontrar ese mismo problema, a mi no me sucedio por el momento y no entiendo como fue originado, y por lo tanto tampoco se como solucionarlo, si es que me das una mano por discord te lo agradeceria una banda, de igual forma, hice un par de arreglos en el state y agregue un par de funciones en las pages para evitar algunos problemas, avisame por favor si el problema persiste!

**Comment by leandromartin114** [comment]
Hola Franco ahí volví a probar el juego y no me tira error. Te quedó muy bueno! Éxito para lo que viene! Saludos
